### ISSUE TITLE
Bitcoin power consumption

### ISSUE THREAD

**Issue by smutt** [nweaver-blockchain/blockchain-names#1]
From namecoin:

"However, this does mean that Namecoin is dependent on Bitcoin’s near criminal levels of energy consumption for securing the system. Bitcoin currency consumes as much power as a medium-sized country."

What's a medium sized country and how much power does it consume? It's a bit like, "How long is a book"?

Something like this would be better, "As of 2023 Bitcoin uses X kWh's and this is as much power as country Y uses in one year."

**Comment by nweaver** [comment]
Added link to digiconimist and estimate.
